# render.yaml
services:
  - type: web
    name: mowsic-player
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
